name: Amber Bracken
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9fa6ac'
    - '#10110c'
    - '#f6f6f6'
    - '#fd9942'
    - '#fdd230'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
