name: Amber Bracken
favicon: null
layout_spectrum: 0.2402
typography_spectrum: 0.6439004566054791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.932770389597863
  lightness: 0.6816325993277133
  saturation: 0.6003939942456782
  rhythmicContrast: 0.07217524899169803
purpose: []
